- value: |
    {{ .Home }}/.dotfiles/scripts/
    {{ .Home }}/bin/
    {{ .Home }}/go/bin/
    {{ .Home }}/.cargo/bin/
  if: eq .OS "linux"

- value: |
    {{ .Home }}/.dotfiles/scripts/
    /opt/homebrew/bin/
    /opt/homebrew/sbin/
    {{ .Home }}/go/bin/
    {{ .Home }}/.cargo/bin/
  if: eq .OS "darwin"
