include ~/.config/omarchy/current/theme/kitty.conf

# Enable splits layout
enabled_layouts splits

# Font
font_family JetBrains Mono Nerd Font
font_size 9

# Window
window_padding_width 10
hide_window_decorations yes
confirm_os_window_close 0

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
allow_remote_control yes

# Aesthetics
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor
enable_audio_bell no

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Splits - Ctrl+Shift+T/D to create, Ctrl+Shift+Arrow to navigate
map alt+shift+t launch --location=hsplit
map alt+shift+d launch --location=vsplit

map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window bottom

# New tab with command
map ctrl+shift+e launch --type=tab --cwd=current --hold zsh -c "yazi; zsh"
map ctrl+shift+a launch --type=tab --cwd=current --hold zsh -c "opencode; zsh"
map ctrl+shift+j launch --type=tab --cwd=current --hold zsh -c "jfsh; zsh"

# Open yazi in current directory (horizontal split)
map ctrl+shift+f launch --location=hsplit --cwd=current zsh -c "yazi"
