include ~/.config/omarchy/current/theme/kitty.conf

# Enable splits layout
enabled_layouts splits

# Font
font_family JetBrains Mono Nerd Font
font_size 9

# Window
window_padding_width 9
hide_window_decorations yes
confirm_os_window_close 0

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
allow_remote_control yes

# Aesthetics
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor
enable_audio_bell yes
background_opacity 0.7
dynamic_background_opacity yes

# Kuroi theme - dark blue tab and border colors
tab_bar_background #0d0d0d
inactive_tab_background #0d0d0d
active_tab_background #3584e4
inactive_tab_foreground #2a2a2a
active_tab_foreground #0d0d0d
tab_bar_border_color #3584e4
active_border_color #3584e4
inactive_border_color #1a1a1a

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
# tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
tab_title_template          {tab.active_exe}

# Splits - Ctrl+Shift+T/D to create, Ctrl+Shift+Arrow to navigate
map alt+shift+t launch --location=hsplit
map alt+shift+d launch --location=vsplit

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window bottom

# New tab with command
map ctrl+shift+e launch --type=tab --cwd=current --hold zsh -c "yazi; zsh"
map ctrl+shift+a launch --type=tab --cwd=current --hold zsh -c "opencode; zsh"
map ctrl+shift+j launch --type=tab --cwd=current --hold zsh -c "jfsh; zsh"

# Open yazi in current directory (horizontal split)
map ctrl+shift+f launch --location=hsplit --cwd=current zsh -c "yazi"
