alias:
  - !include ".aliae/cross.yml"
  - !include ".aliae/nav.yml"
  - !include ".aliae/ls.yml"
  - !include ".aliae/windows/base.yml"
  - !include ".aliae/unix/base.yml"
env:
  - !include ".aliae/env.yml"
