theme: kuroi

radarr:
  - name: Local
    host: zimaos
    port: 7878
    api_token: ***REMOVED***

  - name: Remote
    uri: http://zimaos:7878
    api_token: ***REMOVED***

sonarr:
  - name: Local
    host: zimaos 
    port: 8989
    api_token: ***REMOVED***

  - name: Remote
    uri: http://zimaos:8989
    api_token: ***REMOVED***
