[[mgr.prepend_keymap]]
on  = "o"
run = "open"
args = ["zathura", "--fork"]
desc = "Open PDF"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on  = "b"
run = "plugin bunny"
desc = "Bookmarks"

[[mgr.prepend_keymap]]
on  = "R"
run = "plugin duck-radar"
desc = "Recent files"

[[mgr.prepend_keymap]]
on  = "gd"
run = "plugin vcs-files"
desc = "Git changed files"