[opener]
epuppy = [
    { run = "epuppy %s", block = true, desc = "Epuppy", for = "unix" },
]
glow = [
    { run = "glow -p %s", block = true, desc = "Glow", for = "unix" },
]
edit = [
    { run = "$EDITOR %s", block = true, for = "unix" },
]

[open]
prepend_rules = [
    { url = "*.epub", use = ["epuppy"] },
    { url = "*.md", use = ["glow", "edit", "reveal"] },
]