include=~/.local/share/omarchy/default/mako/core.ini

# Kuroi theme colors
text-color=#ffffff
border-color=#3584e4
background-color=#0d0d0d

# Custom styling
font=JetBrainsMono Nerd Font 14px
border-size=1
border-radius=6
