# Application bindings
unbind = SUPER, X
bindd = SUPER, X, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER ALT, X, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bindd = SUPER, E, Terminal File Manager, exec, omarchy-launch-tui yazi
bindd = SUPER, M, System Monitor, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, J, Jellyfin TUI, exec, omarchy-launch-tui jfsh
bindd = SUPER SHIFT, F, File manager, exec, omarchy-launch-tui spf
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, omarchy-launch-tui spf --cwd "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus g4music
bindd = SUPER CTRL, M, Managarr, exec, omarchy-launch-tui managarr
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- bitwarden
bindd = SUPER SHIFT, A, Opencode, exec, omarchy-launch-tui opencode
bindd = SUPER SHIFT, S, Smassh, exec, omarchy-launch-tui smassh

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
unbind = SUPER, SPACE
unbind = SUPER ALT, SPACE
unbind = SUPER, ESCAPE
bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
bindd = SUPER ALT, SPACE, System menu, exec, omarchy-menu system
bindd = ALT, SPACE, System menu, exec, omarchy-launch-walker

# Waybar toggle (with dynamic top gap)
unbind = SUPER SHIFT, SPACE
unbind = SUPER CTRL, I
bind = SUPER CTRL, I, exec, $DOTFILES_DIR/scripts/idle-toggle
bind = SUPER SHIFT, SPACE, exec, $DOTFILES_DIR/scripts/waybar-toggle

