env = GDK_SCALE,0.7
env = DOTFILES_DIR,$HOME/.dotfiles
env = PATH,$HOME/.local/bin:$DOTFILES_DIR/scripts:$PATH
env = XCURSOR_THEME,WinSur-dark-cursors
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct
env = FILE_MANAGER,yazi
