plugin:overview:panelColor = rgb(111111)
plugin:overview:panelBorderColor = rgb(222222)
plugin:overview:panelBorderWidth = 1
plugin:overview:workspaceActiveBackground = rgb(1a1a1a)
plugin:overview:workspaceInactiveBackground = rgb(0d0d0d)
plugin:overview:workspaceActiveBorder = rgb(555555)
plugin:overview:workspaceInactiveBorder = rgb(333333)
plugin:overview:workspaceBorderSize = 2
plugin:overview:panelHeight = 100
plugin:overview:centerAligned = true
plugin:overview:drawActiveWorkspace = true
plugin:overview:hideBackgroundLayers = true
plugin:overview:hideTopLayers = true
plugin:overview:hideOverlayLayers = true
plugin:overview:overrideGaps = true
plugin:overview:gapsIn = 0
plugin:overview:gapsOut = 0
plugin:overview:exitOnClick = true
plugin:overview:exitOnSwitch = true
plugin:overview:showNewWorkspace = true
plugin:overview:autoScroll = true
