# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 3
    gaps_out = 0, 6, 6, 6
    border_size = 1
    col.active_border = rgb(292929)
    col.inactive_border = rgb(020202)

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 5

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    dim_inactive = true
    dim_strength = 0.5
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = yes
    animation = workspaces, 1, 2, default
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
