windowrule = match:class mpv, border_size 1, tag -floating-window, tile on
windowrule = match:class zen, border_size 1, fullscreen_state 0 2, workspace special:scratchpad
windowrule = match:class code-oss, border_size 1, fullscreen_state 0 2
windowrule = match:class libreoffice-writer, border_size 1

windowrule = match:float true, border_size 1
