alias:
  - !include "../.aliae/core.yml"
  - !include "../.aliae/nav.yml"
  - !include "../.aliae/git.yml"
  - !include "../.aliae/ls.yml"
  - !include "../.aliae/omarchy.yml"
env:
  - !include "../.aliae/env.yml"
script:
  - !include "../.aliae/scripts.yml"
path:
  - !include "../.aliae/path.yml"
