#!/bin/bash
# Toggle hypridle

if pgrep -x hypridle >/dev/null; then
  pkill -x hypridle
  notify-send "󰅶  Caffeine Enabled"
else
  uwsm-app -- hypridle >/dev/null 2>&1 &
  notify-send -u low "󰛊  Caffeine Disabled"
fi

pkill -RTMIN+9 waybar
