#!/bin/bash
# Reload hyprland session

output=$(hyprctl reload 2>&1)

if echo "$output" | grep -q "^ok"; then
  notify-send "  Reloaded" -t "1000"
else
  notify-send -u critical "  Reload failed" "$output" -t "1000"
fi
